version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:15.4-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /root/db_files:/var/lib/postgresql/data
    networks:
      - genixo-network


  genixo-server:
    container_name: liv-parent
    image: ctekkaya/liv-enerji-parent:2.0
    restart: always
    networks:
      - genixo-network
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  genixo-app:
    container_name: liv-app
    image: ctekkaya/liv-enerji-app:2.0
    restart: always
    networks:
      - genixo-network
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  genixo-network:
    name: genixo-network